In [5]:
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.svm import SVC, LinearSVC
from datetime import datetime
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE, ADASYN 
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier,HistGradientBoostingClassifier#, StackingClassifier
from lightgbm import LGBMClassifier
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression, Lasso, RidgeCV, SGDClassifier
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import PCA, KernelPCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from mlxtend.classifier import StackingClassifier
import glob
import os
import pandas as pd
from utils.data import *
from utils.evaluation import *

df = pd.read_csv("ntu-fintech-hw1-new/train.csv", index_col=["index"])
df.head(1)
# preprocessing
## NaN
#df = df.dropna(axis=0)
#df = fill_nan_with_mean_most(df)
df = df.fillna(df.rolling(2, min_periods=1).sum().mean())


## label
#df = labeling(df)
for feature in df.columns:
    df[feature] = labelencoder.fit_transform(df[feature])


#df =  preprocessing_only_label(df)
#X =  preprocessing_onehot(X)
#df =  preprocessing_mean_mode(df)

X = df.drop(['label'],axis=1)
y = df['label']
print(X.shape, y.shape)
X.head(1)

(20000, 17) (20000,)

,age,euducation_level,job,marital,have_credit_card,have_housing_loan,have_personal_loan,connect_method,previous_connect_month,previous_connect_weekday,campaign_connect_times,after_campaign_connect_day,before_campaign_connect_times,last_campaign_outcomes,employment_rate,consumer_price_index,consumer_confidence_index
index,,,,,,,,,,,,,,,,,
0,21,0,0,1,0,0,0,0,7,3,0,1,0,1,7,11,7

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.35)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
X_train.head(1)

(13000, 17) (7000, 17) (13000,) (7000,)

,age,euducation_level,job,marital,have_credit_card,have_housing_loan,have_personal_loan,connect_method,previous_connect_month,previous_connect_weekday,campaign_connect_times,after_campaign_connect_day,before_campaign_connect_times,last_campaign_outcomes,employment_rate,consumer_price_index,consumer_confidence_index
index,,,,,,,,,,,,,,,,,
15241,11,2,0,2,1,2,0,1,6,4,1,1,0,1,8,18,16